-- =========================================================================
-- BORAVIVER VIAGENS - Estrutura Oficial do Banco de Dados (Schema SQL)
-- Ano: 2026
-- Plataforma: Supabase (PostgreSQL)
-- Funcionalidades: RBAC (Roles), Realtime Engine, Relacionamentos e Triggers
-- =========================================================================

-- Habilita extensões necessárias para UUIDs seguros se não existirem
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TABELA DE USUÁRIOS E PERFIS ESTENDIDOS (Integração com Supabase Auth)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    nome VARCHAR(80) NOT NULL,
    sobrenome VARCHAR(80) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    whatsapp VARCHAR(20),
    role VARCHAR(20) DEFAULT 'CLIENT' CHECK (role IN ('ADMIN', 'CLIENT')),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. TABELA DE LINKS DINÂMICOS DE VIAGEM (Passagens, Hospedagens, Pacotes)
CREATE TABLE public.travel_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('PASSAGEM', 'HOSPEDAGEM', 'PACOTE')),
    nome VARCHAR(150) NOT NULL,
    url TEXT NOT NULL,
    status BOOLEAN DEFAULT TRUE NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. TABELA DE PROMOÇÕES E OFERTAS RELÂMPAGO (Para os Banners Reativos)
CREATE TABLE public.promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    destino VARCHAR(100) NOT NULL,
    valor NUMERIC(12, 2) NOT NULL,
    descricao TEXT NOT NULL,
    imagem TEXT,
    data_validade DATE NOT NULL,
    status BOOLEAN DEFAULT TRUE NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. TABELA DE CONFIGURAÇÕES INSTITUCIONAIS DA MARCA (Registro Único ID 1)
CREATE TABLE public.company_settings (
    id INT PRIMARY KEY CHECK (id = 1), -- Garante registro estrito único
    empresa VARCHAR(100) DEFAULT 'BORAVIVER VIAGENS' NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    sobre TEXT,
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. TABELA DE HISTÓRICO DE SIMULAÇÕES (Auditoria do Admin)
CREATE TABLE public.simulations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    item_nome VARCHAR(150) NOT NULL,
    quantidade INT DEFAULT 1 NOT NULL,
    valor_total NUMERIC(12, 2) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- =========================================================================
-- CONFIGURAÇÃO DO RELEATIME ENGINE DO SUPABASE (Publish/Subscribe)
-- =========================================================================

-- Adiciona as tabelas críticas para o canal de replicação em tempo real do Supabase
ALTER PUBLICATION supabase_realtime ADD TABLE public.promotions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.travel_links;
ALTER PUBLICATION supabase_realtime ADD TABLE public.simulations;

-- =========================================================================
-- POPULAÇÃO INICIAL DE DADOS (Seed Primário de Segurança)
-- =========================================================================

-- Inserção padrão das configurações organizacionais centrais
INSERT INTO public.company_settings (id, empresa, whatsapp, email, sobre)
VALUES (
    1, 
    'BORAVIVER VIAGENS', 
    '5511999999999', 
    'diretoria@boraviverviagens.com.br', 
    'Agência boutique focada em experiências imersivas e turismo premium internacional.'
) ON CONFLICT (id) DO NOTHING;

-- Inserção de uma promoção inicial padrão para alimentar os feeds
INSERT INTO public.promotions (titulo, destino, valor, descricao, data_validade)
VALUES (
    'Maldivas Summer Experience', 
    'Ilhas Maldivas Resort', 
    7890.00, 
    'Bangalô sobre a água com tudo incluso, transfer privativo e taxas aéreas bonificadas por tempo limitado.', 
    '2026-12-31'
);